Made "Medication, Order" cumulative medication duration calculate correctly.
MeasureAuthoringTool/health-data-standards pull request #421
Opened 2016-08-18 13:30 UTC by edeyoung

This addresses https://oncprojectracking.healthit.gov/support/browse/BONNIE-172.

Usually, cumulative medication duration is calculated based off of the fulfillment history, dose, and regimen. However, for "Medication, Order", the medication has not yet been filled, so fulfillment history and dose don't make sense. Maybe more importantly, these fields are not available in the QRDA for the "Medication, Order" template.

Instead, cumulative medication duration should be calculated based on the maximum allowed administrations (`repeatNumber` in the QRDA) and the regimen (`effectiveTime` with `period` subelement in the QRDA).

Additionally, fulfillment information should not be allowed to be entered for "Medication, Order".

Specific changes for this repository include adding `allowedAdministrations` to the medication model and including `repeateNumber` in the "Medication, Ordered" QRDA templates.

This pull request depends on the `medication_order_cmd` branches in **bonnie, hqmf2js, and patient-api.**

2016-10-18 13:47 UTC, okeefm requested changes

2016-10-18 13:47 UTC, okeefm commented on templates/cat1/_2.16.840.1.113883.10.20.24.3.47.cat1.erb
> +      <repeatNumber value="<%== entry.allowedAdministrations %>" />
Do we want to be able to re-import this field again? If so, we should add something to the `CDA::MedicationImporter` (which imports this template currently), or subclass it and create a `Cat1::MedicationImporter`

2016-10-25 16:34 UTC, thecristen requested changes
I think mokeefe's comment should be addressed, other than that I'd say we're good to go.

2016-10-25 16:35 UTC, thecristen approved these changes

2016-10-26 00:38 UTC, okeefm approved these changes
Changes look good to me.

2016-10-26 11:38 UTC, merged