Qrda 3.1 validation
MeasureAuthoringTool/health-data-standards pull request #438
Opened 2016-10-25 14:25 UTC by alexanderelliott121

Change the way the qrda version is passed through, how templates are stored and template logic surrounding qrda version.

2016-10-25 15:25 UTC, edeyoung requested changes
a key thing to figure out is how this will handle an unspecified or bad `qrda_version`.

2016-10-25 15:25 UTC, edeyoung commented on lib/health-data-standards/export/qrda/entry_template_resolver.rb
> +            qrda_version == 'r3_1' ? '2.16.840.1.113883.10.20.24.3.103' : '2.16.840.1.113883.10.20.24.3.103'
are these the same ids in either case now? if so, can we remove the `...?...:...` stuff and just return the one oid?

2016-10-25 15:25 UTC, edeyoung commented on lib/health-data-standards/export/qrda/entry_template_resolver.rb
> +              '2.16.840.1.113883.10.20.24.3.103'
can you have `or`s in `when` statements? If so, combine `when 'r3_1'` and `when 'r3'`.

2016-10-25 15:25 UTC, edeyoung commented on lib/health-data-standards/export/qrda/entry_template_resolver.rb
> +            qrda_version == 'r3_1' ? '2.16.840.1.113883.10.20.24.3.103' : '2.16.840.1.113883.10.20.24.3.103'
See above. you can get rid of the `...?...:...` stuff here.

2016-10-25 15:25 UTC, edeyoung commented on lib/health-data-standards/export/cat_1.rb
> -        # defaults to QRDA R3 'show' templates (prior to version specific templates)
what happens if the `qrda_version` isn't specified? Does this fail gracefully? There are two situations we should consider:
- `nil` is passed in. In this case, we should consider defaulting to some version (the latest?)
- an unexpected value is passed in. In this case, we should error gracefully with an explanatory error message.

2016-10-25 15:25 UTC, edeyoung commented on lib/health-data-standards/export/template_helper.rb
> +        subdir = provided_qrda_version if provided_qrda_version
should there be some sort of error if the qrda versions don't align?

does it make sense to only specify the qrda version in one place - either in the template helper or the renderer (currently it can be passed in in either) so this kind of conflict can't occur?

2016-10-25 15:25 UTC, edeyoung commented on templates/cat1/r2/_2.16.840.1.113883.10.20.24.3.9.cat1.erb
> +    <templateId root="2.16.840.1.113883.10.20.22.4.43" <% if !r2_compatibility %>extension="2014-06-09"<%end%>/>
is the plan still to go back through the `r2` templates and remove the `r2_compatibility` flags? These aren't needed anymore. I remember we discussed removing them and decided that in the short term we would just do `r3` and `r3_1`. Am I remembering correctly?

2016-10-25 15:25 UTC, edeyoung commented on templates/cat1/r3/_2.16.840.1.113883.10.20.24.3.9.cat1.erb
> +    <templateId root="2.16.840.1.113883.10.20.22.4.43" <% if !r2_compatibility %>extension="2014-06-09"<%end%>/>
are these `r2_compatibility` flags generally still present in the `r3` templates? is this one of the "future change" things? I had it in my head it was only the `r2` files that weren't going to be changed, but if it's these too, that's fine and good to know.

2016-10-25 15:36 UTC, edeyoung commented
`r3` template `2.16.840.1.113883.10.20.24.3.103.cat1.erb` has the incorrect date associated with it. It has "2016-02-01". It should have "2014-12-01".

2016-10-25 18:00 UTC, okeefm commented on lib/health-data-standards/export/qrda/entry_template_resolver.rb
> +              '2.16.840.1.113883.10.20.24.3.103'
You can't have `or`s, but you can basically do the same thing with `when 'r3_1','r3'`

2016-10-26 14:56 UTC, mayerm94 commented on templates/cat1/r3/_2.16.840.1.113883.10.20.24.3.9.cat1.erb
> +    <templateId root="2.16.840.1.113883.10.20.22.4.43" <% if !r2_compatibility %>extension="2014-06-09"<%end%>/>
r2_compatibility flags have been removed entirely from the r3 templates

2016-10-26 15:05 UTC, mayerm94 commented on templates/cat1/r2/_2.16.840.1.113883.10.20.24.3.9.cat1.erb
> +    <templateId root="2.16.840.1.113883.10.20.22.4.43" <% if !r2_compatibility %>extension="2014-06-09"<%end%>/>
Correct, the r2_compatibility flags will be left in r2 for the time being. However, the r2_compatibility flags have been stripped out of r3 and r3_1

2016-10-26 15:14 UTC, alexanderelliott121 commented on lib/health-data-standards/export/template_helper.rb
> +        subdir = provided_qrda_version if provided_qrda_version
The implementation was set up to accommodate preexisting architecture.
I've added a todo to rectify it.

2016-10-27 17:33 UTC, alexanderelliott121 commented
I've added a check to cat1 that sets a nil qrda_version to the latest.

2016-10-27 19:57 UTC, okeefm commented on lib/health-data-standards/export/cat_1.rb
> -        # defaults to QRDA R3 'show' templates (prior to version specific templates)
Could also rewrite this to be a `case` statement similar to other locations in the code, to make it cleaner.

2016-10-28 13:53 UTC, okeefm commented on templates/cat1/r2/show.cat1.erb
> +  <templateId root="2.16.840.1.113883.10.20.24.1.1" extension="2014-12-01" />
I'm not sure I understand why the `if` statement was removed here, but the same `if` statement is present in other cat1 r2 files.

2016-11-01 15:20 UTC, alexanderelliott121 commented on templates/cat1/r2/show.cat1.erb
> +  <templateId root="2.16.840.1.113883.10.20.24.1.1" extension="2014-12-01" />
Long story short, we decided that we would focus on the r3 and r3_1 templates.  That r2 was changed at some point, the rest will be addressed in future work.

2016-11-01 15:23 UTC, edeyoung commented on templates/cat1/r2/show.cat1.erb
> +  <templateId root="2.16.840.1.113883.10.20.24.1.1" extension="2014-12-01" />
i think the problem @okeefm is mentioning is that this template *was* changed in r2. It looks like this change was in error - it makes the template always include date flags that should not be in an r2 template.

2016-11-04 16:10 UTC, dczulada commented on templates/cat1/r3_1/_2.16.840.1.113883.10.20.24.3.23.cat1.erb
>      <templateId root="2.16.840.1.113883.10.20.24.3.23" extension="2016-02-01"/>
In QRDA 3.1 the encounter performed template must be contained in the Encounter Performed Act template to represent the Encounter, Performed QDM data type.

![screen shot 2016-11-04 at 12 10 25 pm](https://cloud.githubusercontent.com/assets/8173551/20012937/b6cc0b1e-a287-11e6-8631-6c6026dce0e6.png)

2016-11-28 16:42 UTC, dczulada commented on lib/health-data-standards/export/qrda/hqmf-qrda-oids.json
>      "hqmf_name": "Device, Intolerance",
Device, Order and Device, Order not done still have "r3_1": "2016_02_01"

2016-11-28 16:46 UTC, dczulada commented on lib/health-data-standards/export/qrda/entry_template_resolver.rb
>            when '2.16.840.1.113883.3.526.3.1279'
"#{'_'+oid_tuple[qrda_version] if oid_tuple[qrda_version]}"  is no longer needed

should only be 

"#{oid_tuple['qrda_oid']}"

2016-11-29 16:42 UTC, edeyoung commented
This work has been incorporated into bonnie_master_2016, which has a pull request into HDS master.

2016-11-29 16:42 UTC, closed without merging