BONNIE-207 Add cache reset to beginning of export.
MeasureAuthoringTool/health-data-standards pull request #452
Opened 2016-11-29 14:08 UTC by alexanderelliott121

Adds a cache clear to the scooped_view_helper.
Invokes scooped_view_helper cache clear at the beginning of export.

2016-11-29 17:00 UTC, edeyoung requested changes

2016-11-29 17:00 UTC, edeyoung commented on lib/health-data-standards/export/helper/scooped_view_helper.rb
> +        def clear_vs_map(bundle_id=nil)
add comment explaining what this should be used for (clearing cache before each export)

2016-11-29 17:00 UTC, edeyoung commented on lib/health-data-standards/export/cat_1.rb
> +        clear_vs_map(patient.bundle_id)
add comment explaining why the cache is being cleared.

2016-11-29 17:00 UTC, edeyoung commented on lib/health-data-standards/export/helper/scooped_view_helper.rb
> +        def clear_vs_map(bundle_id=nil)
i don't think `bundle_id` should be optional here. What do you think? Or if it is `nil`, should we be grabbing `latest_bundle_id` as well, like is done below? or is that too risky?

2016-11-30 18:08 UTC, alexanderelliott121 commented on lib/health-data-standards/export/helper/scooped_view_helper.rb
> +        def clear_vs_map(bundle_id=nil)
It makes sense to use the latest bundle id, since that is the cache that will be accessed.

2016-12-14 23:54 UTC, okeefm commented on lib/health-data-standards/export/helper/scooped_view_helper.rb
> +        def clear_vs_map(bundle_id=nil)
Looks like @edeyoung's comment here was addressed (by grabbing `latest_bundle_id`) in the commit below, but the GitHub system didn't pick it up.

2016-12-14 23:56 UTC, okeefm approved these changes
Looks good to me.

2016-12-15 13:11 UTC, edeyoung approved these changes

2016-12-15 13:12 UTC, edeyoung commented
@okeefm it looks like these changes are against bonnie_master_2016 and should actually be applied to the master branch.

2016-12-15 14:54 UTC, okeefm commented
@edeyoung Looks like this is @alexanderelliott121's pull request. Can he

2016-12-15 14:54 UTC, closed without merging