Null flavor mongoid5
MeasureAuthoringTool/health-data-standards pull request #464
Opened 2016-12-22 21:41 UTC by dczulada

2016-12-22 21:41 UTC, dczulada commented
This still needs tests

2017-01-05 18:30 UTC, okeefm requested changes

2017-01-05 18:30 UTC, okeefm commented on lib/health-data-standards/import/cda/medication_importer.rb
> +            #extract_negated_code(parent_element, medication) if medication.codes.empty?
Is there a reason this commented out code is here?

2017-01-05 18:30 UTC, okeefm commented on lib/health-data-standards/import/cda/section_importer.rb
> +          coded_parent_element = parent_element unless coded_parent_element
can replace this with `coded_parent_element ||= parent_element`

2017-01-05 20:27 UTC, dczulada commented
@okeefm updated

2017-01-05 20:59 UTC, okeefm approved these changes

2017-01-05 20:59 UTC, merged