Qdm 5.01 cql
MeasureAuthoringTool/health-data-standards pull request #483
Opened 2017-03-29 18:22 UTC by mayerm94

These include the addition of the components attribute added in the QDM 5.01 document.

2017-04-05 13:40 UTC, edeyoung requested changes

2017-04-05 13:40 UTC, edeyoung commented on lib/health-data-standards/models/procedure.rb
> +  field :components,           type: Hash
nit pick, but watch spacing for things like `type: Hash` where they are aligned. Similar for other files.

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-model/data_criteria.rb
> +              'COMPONENT' => {title: 'Component', coded_entry_method: :components, code: '1234567', code_system: '2.16.840.1.113883.6.96', field_type: :value},
rather than use fake codes, remove the `code` and `code_system` fields. When a fake code is necessary, use something very obvious. For example, make the `code_system` here by `1.11.111.111...`.

See `RESULT_DATETIME` as an example.

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-model/data_criteria.rb
> +                    '1234567'   => 'COMPONENTS',
You can remove this given the suggestion to remove the code from above. `VALUE_FIELDS` not necessary for CQL parsing.

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-model/data_criteria.rb
> +          value = HQMF::GenericCollection.from_json(json)
Consider renaming from `GenericCollection` to `Collection`

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-model/types.rb
> -
be careful of changes that are just whitespace changes. Try to catch these when doing diffs pre-commit.

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-model/types.rb
> +      HQMF::GenericCollection.new(type,values)
watch spacing: `type,values` -> `type, values`

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-model/types.rb
> +      @type = 'CMP'
Should this be `@type = type || 'COM'` like the others are?

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-model/types.rb
> +      #hash[:range] = @range.to_json if @range
add TODO here

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-parser/cql/document.rb
> +        # REVIEW: For HQMF + CQL, do we need both DC and SDC?
remove comment this.

for now, i think we do because of how the bonnie interface uses both DC and SDC. If we were to rework that, maybe not.
@holmesie what are your thoughts?

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-parser/cql/document.rb
> +            @populations_cql_map[criteria_id] = cql_statement.to_s.delete('\\"')
was this necessary for your changes or a simplification that you noticed could be implemented? if a simplification, please revert and include in another PR so we can test any effects of this separately. if necessary, please explain. the code looks like it removes some checks and default behavior that may be important.

2017-04-05 13:40 UTC, edeyoung commented on lib/hqmf-parser/cql/population_helper.rb
> +module HQMF2CQL
is this class used anywhere or necessary? It looks like it might be left-over from a previous idea.

2017-04-05 13:40 UTC, edeyoung commented on test/unit/hqmf/cql/hqmf_cql_test.rb
> +    if ["1"].index(measure_name)
why is this updated to `'1'`?

2017-04-05 14:50 UTC, mayerm94 commented on test/unit/hqmf/cql/hqmf_cql_test.rb
> +    if ["1"].index(measure_name)
Not sure, this was pulled in from the rebase in commit https://github.com/projectcypress/health-data-standards/pull/483/commits/bb5d9b458c718301236c696a48483c70d746773c

2017-04-05 14:54 UTC, mayerm94 commented on test/unit/hqmf/cql/hqmf_cql_test.rb
> +    if ["1"].index(measure_name)
It is worth noting that there is no difference in test result when either 1 or 2 is used

2017-04-13 19:59 UTC, mayerm94 commented on lib/hqmf-parser/cql/population_helper.rb
> +module HQMF2CQL
I believe this class is still used, the changes to incorporate stratification parsing (which was reverted) was originally made in this file in the extract_populations_cql_map. I believe that particular function has since been moved to document_helpers/doc_population_helper.rb

2017-04-14 18:51 UTC, edeyoung approved these changes

2017-04-14 18:52 UTC, edeyoung commented
still need to test end-to-end with the other changes made to support QDM 5.01

2017-04-17 14:24 UTC, edeyoung requested changes
the reference to population_helper needs to be removed from health-data-standards/lib/hqmf-parser.

2017-04-18 13:43 UTC, edeyoung commented
There were issues with the commit stack for this request. this got addressed in this PR: https://github.com/projectcypress/health-data-standards/pull/490

2017-04-18 13:43 UTC, closed without merging