support QRDA Cat I R4
MeasureAuthoringTool/health-data-standards pull request #491
Opened 2017-04-18 14:24 UTC by dczulada

2017-04-18 15:13 UTC, edeyoung reviewed
What is the priority of this pull request? This has significant impact on Bonnie and may take us time to review thoroughly.

2017-04-18 15:50 UTC, dczulada commented
No hurry on this review.

2017-05-04 19:18 UTC, alexanderelliott121 commented
Are there any test fixture that we can use to validate that the qrda being exported is valid?

2017-05-05 17:59 UTC, dczulada commented
Just added schematron validation to the Cat I  unit test

2017-05-05 18:08 UTC, mayerm94 commented
For anyone else reviewing: These are the QRDA changes for r4
![image](https://cloud.githubusercontent.com/assets/3967953/25758262/d45368e6-319b-11e7-8540-e00f052eb1e2.png)
And these are the corresponding  QDM4.3 changes from https://ecqi.healthit.gov/system/files/qdm_4_3_508_compliant.pdf
![image](https://cloud.githubusercontent.com/assets/3967953/25758284/ee307bb4-319b-11e7-9227-c983bc082e65.png)

2017-05-08 12:53 UTC, mayerm94 requested changes

2017-05-08 12:53 UTC, mayerm94 commented on lib/health-data-standards/export/cat_1.rb
>        def export(patient, measures, start_date, end_date, header=nil, qrda_version='r3_1', cms_compatibility=false)
The comment says "default qrda_version should be latest version, should this be r4 now instead of r3_1

2017-05-08 12:53 UTC, mayerm94 commented on lib/health-data-standards/export/qrda/hqmf-qrda-oids.json
> +    "qrda_oid": "2.16.840.1.113883.10.20.24.3.145"
I do not see a template added for assessment recommended in templates/cat1/r4/

2017-05-08 12:53 UTC, mayerm94 commented on templates/cat1/r4/_2.16.840.1.113883.10.20.24.3.26.cat1.erb
> + <entry>
This template was retired in r4

2017-05-09 15:15 UTC, alexanderelliott121 commented
I can't find any issues beyond what Matt has already highlighted.

2017-05-30 16:05 UTC, mayerm94 approved these changes

2017-06-06 18:57 UTC, dczulada commented on lib/health-data-standards/export/qrda/hqmf-qrda-oids.json
> +    "qrda_oid": "2.16.840.1.113883.10.20.24.3.145"
2.16.840.1.113883.10.20.24.3.145 template was added.

2017-06-07 15:54 UTC, okeefm approved these changes

2017-06-08 13:13 UTC, tstrass commented on templates/cat1/r4/_2.16.840.1.113883.10.20.24.3.135.cat1.erb
> +    <statusCode code="active" />
Looks like `code` can either be "active" or "completed" in R4, per [this valueset](https://vsac.nlm.nih.gov/valueset/2.16.840.1.113762.1.4.1021.35/expansion).

2017-06-08 13:18 UTC, okeefm commented on templates/cat1/r4/_2.16.840.1.113883.10.20.24.3.135.cat1.erb
> +    <statusCode code="active" />
Good catch. Took a look at the IG and it confirms the value for `<statusCode>` should be coming from that valueset.

2017-06-08 15:20 UTC, okeefm requested changes
Should review the use of `<statusCode>active</statusCode>` as pointed out by @tstrass

2017-06-28 16:07 UTC, closed without merging