Support QRDA Cat III R2.1 export
MeasureAuthoringTool/health-data-standards pull request #510
Opened 2017-07-11 13:56 UTC by dczulada

Add QRDA Cat III R2.1 schematron validator

2017-07-19 16:50 UTC, tstrass approved these changes

2017-07-20 16:22 UTC, edeyoung approved these changes
I have not had a chance to check the QRDA or have someone on my team do it. However, since this is related to cat_3 and the rest of the logic looks sound to me, I approve.

2017-07-20 18:47 UTC, okeefm requested changes

2017-07-20 18:47 UTC, okeefm commented on templates/cat3/r2_1/_measure_data.cat3.erb
> +  <!--  Startification Reporting Template for <%= population.type %>  <%= population.id %>  Stratification <%= strat.id %>   -->
`Startification` should be `Stratification`

2017-07-20 18:47 UTC, okeefm commented on templates/cat3/r2_1/_measure_data.cat3.erb
> + <!--         PAYER Supplemental Data Reporting   for<%= population.type %>  <%= population.id %>   -->
Can you add a space between `Data reporting for` and `<%= population.type %>`

2017-07-20 18:47 UTC, okeefm commented on templates/cat3/r2_1/_supplemental_data.cat3.erb
> +  <!--                            Supplemental Date Template                                                  -->
This should say `supplemental Data` not `Supplemental Date`

2017-07-20 19:01 UTC, okeefm approved these changes

2017-07-20 19:02 UTC, merged