Cql4bonnie qdm5 3 937
MeasureAuthoringTool/health-data-standards pull request #523
Opened 2017-08-03 20:30 UTC by losborne

JIRA Test: https://jira.mitre.org/browse/BONNIE-961

2017-08-04 11:46 UTC, mayerm94 commented on lib/hqmf-parser/cql/document_helpers/doc_population_helper.rb
> -            unless populations_cql_map[criteria_id].include? cql_statement
What was the motivation for removing this?

2017-08-04 13:34 UTC, edeyoung commented on lib/hqmf-parser/cql/document_helpers/doc_population_helper.rb
> -            unless populations_cql_map[criteria_id].include? cql_statement
hm... it looks like the cql4bonnie-QDM_5-3 branch needs the latest merge from cql4bonnie (this was a bug fix a bit ago), and it looks like luke originally branched from cql4bonnie.

2017-08-04 13:37 UTC, edeyoung commented on lib/hqmf-parser/cql/document_helpers/doc_population_helper.rb
> -            unless populations_cql_map[criteria_id].include? cql_statement
I just did that. the PR doesn't seem to be updating though.

2017-08-04 17:07 UTC, jbradl11 approved these changes
This looks good, if we are ok with breaking backwards compatibility. By changing the model, I believe this will break previous versions. Test passed.

2017-08-04 17:16 UTC, mayerm94 approved these changes

2017-08-04 17:44 UTC, edeyoung commented on lib/health-data-standards/models/encounter.rb
> +  embeds_one :diagnoses, class_name: "EncounterPrincipalDiagnosis"
does this not need to change to `embeds_many`?

2017-08-04 17:45 UTC, edeyoung requested changes
respond to `embeds_many` question

2017-08-04 17:52 UTC, losborne commented on lib/health-data-standards/models/encounter.rb
> +  embeds_one :diagnoses, class_name: "EncounterPrincipalDiagnosis"
The encounter has one 'diagnoses' field, which is an array of diagnoses, rather than embedding many singular diagnosis fields.

2017-08-04 18:37 UTC, edeyoung commented on lib/health-data-standards/models/encounter.rb
> +  embeds_one :diagnoses, class_name: "EncounterPrincipalDiagnosis"
I'm blanking on this. Is it an array simply because we assign an array to it at some point? Have you confirmed that it actually gets stored in the db as an array? I don't see any changes below that indicate that diagnoses is now an array, which is why i'm asking.

thanks!

2017-08-04 19:06 UTC, losborne commented on lib/health-data-standards/models/encounter.rb
> +  embeds_one :diagnoses, class_name: "EncounterPrincipalDiagnosis"
I looked to how components was handled in health_data_standards, which is like this:
![image](https://user-images.githubusercontent.com/14879344/28982557-4dc139ae-7924-11e7-9e97-3f1188b2e0e8.png)
I thought that embeds_one would be similar to field in this case.

The database shows that diagnoses is of the Collection type that Matt made:
![image](https://user-images.githubusercontent.com/14879344/28983156-68a132c2-7926-11e7-9529-31e675dfded6.png)

The values represent the individual diagnosis elements.

2017-08-07 20:58 UTC, edeyoung approved these changes

2017-08-08 13:03 UTC, merged