Add logic that will find where there is only a negated data criterion…
MeasureAuthoringTool/health-data-standards pull request #525
Opened 2017-08-04 13:31 UTC by mulcahyk

Moves the logic that checks for only negated data criteria from bonnie-bundler into HDS.
Goes with https://github.com/projecttacoma/bonnie_bundler/pull/101

JIRA test: https://jira.mitre.org/browse/BONNIE-839

2017-08-04 14:51 UTC, holmesie commented on lib/hqmf-parser/cql/document.rb
> +        # description_hash[criterion] = detail['description']
Is this part of the comment? Or just commented out code?

2017-08-04 14:54 UTC, holmesie commented on lib/hqmf-parser/cql/document.rb
> +            description = description.gsub(', Not', ', ')
With this `gsub`, `Encounter, Not Performed` would be turned into `Encounter,  Performed` (two spaces between the `,` and `Performed`). I think it should be `description = description.gsub(', Not', ',')` instead.

2017-08-04 15:11 UTC, holmesie commented on lib/hqmf-parser/cql/data_criteria.rb
> +      @description = "#{@description}: #{title}" if (/: #{title}$/).match(@description).nil?
Why this change? Seems to make sense, but just am curious.

2017-08-04 15:14 UTC, holmesie commented on lib/hqmf-parser/cql/document.rb
> +            spoofed_criterion_name = spoofed_title + '_' + spoofed_def + spoofed_status + '_spoofed'
I'm not seeing where this variable is being used.

2017-08-04 15:18 UTC, holmesie commented on lib/hqmf-parser/cql/document.rb
> +            description = description.gsub(', Not', ', ')
Also, you can do a `description.gsub!(', Not', ',')` instead here - not a biggie, but is a nice shortcut.

2017-08-04 16:14 UTC, mulcahyk commented on lib/hqmf-parser/cql/data_criteria.rb
> +      @description = "#{@description}: #{title}" if (/: #{title}$/).match(@description).nil?
If I don't do this it will add a second : #{title}.  It has to do with the cql version of this file inheriting from the qdm version of the file.  I couldn't find where the first `retrieve_title_and_description_for_model` was being called.

2017-08-04 16:17 UTC, mulcahyk commented on lib/hqmf-parser/cql/document.rb
> +        # description_hash[criterion] = detail['description']
Old comment.  Removing.

2017-08-04 17:06 UTC, edeyoung commented on lib/hqmf-parser/cql/data_criteria.rb
> +      @description = "#{@description}: #{title}" if (/: #{title}$/).match(@description).nil?
where did you see this? Was this during debugging? Is there a change in the code that now makes this get called multiple times?

I'm very confident that in practice, this only gets called once.

2017-08-04 17:12 UTC, edeyoung commented on lib/hqmf-parser/cql/document.rb
> +        data_criteria_index_lookup[source_index] = [criterion.code_list_id, criterion.definition, criterion.status, criterion.negation]
why is this a hash instead of an array? It never gets used effectively as a hash (using the key for quick access).

2017-08-04 17:29 UTC, mulcahyk commented on lib/hqmf-parser/cql/data_criteria.rb
> +      @description = "#{@description}: #{title}" if (/: #{title}$/).match(@description).nil?
I thought it was strange as well.  I actually only saw it on my final round of testing when I was making sure that everything for the spoofed entries matched the nature entries.  As far as I can tell I didn't change anything that would make this get called multiple times.  Perhaps there is something in the onion a few layers down that I just don't know about..?

2017-08-04 17:35 UTC, edeyoung commented on lib/hqmf-parser/cql/data_criteria.rb
> +      @description = "#{@description}: #{title}" if (/: #{title}$/).match(@description).nil?
can you remove this change, try again, and document exactly what you're seeing and what was executed to see this (e.g., through an automated test, through starting the server and uploading a measure in bonnie, through a debugger view, etc.)?

Thank will give me greater comfort for this change.

2017-08-04 17:41 UTC, c-monkey approved these changes
Passed https://jira.mitre.org/browse/BONNIE-839. Code is basically the same as source.

2017-08-04 18:08 UTC, c-monkey commented
Can we create an automated test for this? Should we?

2017-08-04 18:19 UTC, c-monkey commented on lib/hqmf-parser/cql/document.rb
> +            spoofed_criterion_name = spoofed_title + '_' + spoofed_def + spoofed_status + '_spoofed'
actually all 4 of the variables with the prefix "spoofed" are obsolete, please remove.

2017-08-04 19:01 UTC, c-monkey requested changes
Sorry I approved this before without a proper code inspection.

2017-08-04 19:01 UTC, c-monkey commented on lib/hqmf-parser/cql/document.rb
> +        negated_criteria.each do |negated_index, criterion|
`negated_index` is not used, how about change `negated_criteria` to an array?

2017-08-04 19:01 UTC, c-monkey commented on lib/hqmf-parser/cql/document.rb
> +            criterion.instance_variable_set(:@negation, false)
This changes the original criterion in @data_criteria. Did you mean to instead make a copy? If not, then the code below `@data_criteria << criterion` doesn't do anything

2017-08-04 19:01 UTC, c-monkey commented on lib/hqmf-parser/cql/document.rb
> +            description = criterion.description
`description` is a pointer to the field, so changing it updates the value in criterion.description

2017-08-07 21:14 UTC, edeyoung commented on lib/hqmf-parser/cql/document.rb
> +            smiley_face = criterion.clone
you still have `smiley_face` :)

2017-08-07 21:14 UTC, edeyoung commented on lib/hqmf-parser/cql/document.rb
> +      data_criteria_index_lookup = {}
looks like my question about this being a hash instead of an array got lost.

this is treated like an array (only looking things up by value). Why not make it be an array? It's not used effectively as a hash (referenced by key).

2017-08-07 21:14 UTC, edeyoung commented on lib/hqmf-parser/cql/document.rb
> +      unless negated_criteria.count == 0
you don't need this check. an empty array just doesn't have element to iterate over.

2017-08-07 21:14 UTC, edeyoung commented on lib/hqmf-parser/cql/document.rb
> +      description_hash = {}
it doesn't look like this gets used.

2017-08-07 22:06 UTC, c-monkey approved these changes
Test passes: https://jira.mitre.org/browse/BONNIE-839

My comments were addressed.

2017-08-08 13:29 UTC, holmesie approved these changes
Test passes, looks good!

2017-08-08 13:38 UTC, merged