Cql4bonnie 1028
MeasureAuthoringTool/health-data-standards pull request #533
Opened 2017-08-31 11:40 UTC by mayerm94

Test with Bonnie cql4bonnie_1028

2017-08-31 13:07 UTC, losborne commented on lib/hqmf-model/types.rb
> +      "#{numerator? '\''}#{denominator}"
What is the stringified ratio supposed to look like?  I believe this will turn numerator=5 and denominator=6 into "5 '6" ? Unless I'm misinterpreting the ruby syntax

2017-08-31 16:22 UTC, holmesie requested changes

2017-08-31 16:22 UTC, holmesie commented on lib/hqmf-model/types.rb
> +
Remove this empty line.

2017-08-31 16:22 UTC, holmesie commented on lib/hqmf-model/types.rb
> +    def numerator?
This is a bit confusing to me. Is the purpose of this method to say if this `Ratio` has a numerator? If so, since the `?` means this is a predicate method, I would recommend making sure you are actually returning a boolean, rather than just relying on the truthiness of `@numerator`. An easy way of doing that is to prepend `@numerator` with `!!`.

If the purpose of this was to actually return the numerator value, since you delcared this variable with `attr_accessor`, you get the read/write methods for free.

2017-08-31 16:22 UTC, holmesie commented on lib/hqmf-model/types.rb
> +    def denominator?
See comment about `def numerator?`.

2017-09-01 00:40 UTC, holmesie approved these changes

2017-09-05 14:03 UTC, edeyoung commented
RATIO WORK NO LONGER BEING USED AS OF 9/1 DISCUSSION IN HQMF CQL TOOLING CALL

2017-09-05 14:03 UTC, closed without merging