BONNIE-1072 VSAC Call Changes
MeasureAuthoringTool/health-data-standards pull request #543
Opened 2017-09-28 12:48 UTC by alexanderelliott121

Intent of PR is to bring the HDS vsac API into conformity with the vsac web api.

JIRA: https://jira.mitre.org/browse/BONNIE-1072
Tests: Automated

- [X] This pull request describes *why* these changes were made.
- [X] Tests are included and test edge cases
- [X] Link to JIRA test(s), if used: NA
- [X] JIRA test(s) have been added to sprint, if used NA
- [X] JIRA ticket for this PR: 
- [X] JIRA ticket links to this PR.
- [ ] Automated regression test(s) pass (if applicable): 

Reviewer 1:
- [ ] The code is maintainable
- [ ] The code reuses code or resources within the project ecosystem where applicable
- [ ] The code achieves its purpose
- [ ] The tests appropriately test edge cases
- [ ] The tests pass

Reviewer 2:
- [ ] The code is maintainable
- [ ] The code reuses code or resources within the project ecosystem where applicable
- [ ] The code achieves its purpose
- [ ] The tests appropriately test edge cases
- [ ] The tests pass

2017-10-03 19:57 UTC, hossenlopp requested changes
I like the addition of the MalformedVSQueryError. It makes sure a hidden default doesn't accidentally get used. There's a few small checks and tests that could be improved.

2017-10-03 19:57 UTC, hossenlopp commented on lib/health-data-standards/util/vs_api.rb
> +        if profile.nil? && include_draft
Perhaps this should also check if it is an empty string.

2017-10-03 19:57 UTC, hossenlopp commented on test/unit/util/vs_api_test.rb
> +    valueset_xml = %{<?xml version="1.0" encoding="UTF-8"?><RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" cacheExpiration
This line isn't needed for this test.

2017-10-03 19:57 UTC, hossenlopp commented on test/unit/util/vs_api_test.rb
>    def test_api_v2_with_include_draft_specified_profile
This existing test does execute the case where both `includeDraft` is `true` and `profile` is provided. It should, if possible, assert that the MalformedVSQueryError isn't thrown.

I noticed an existing issue with this test. All of the asserts for this test are in the block provided to get_valueset. If get_valueset returns early due to an introduced defect, then it won't yield anything and no asserts will occur. Therefore, this test may fail detect defects. The return result of the `get_valueset` function should be used to check the result of the test call.

2017-10-03 20:00 UTC, hossenlopp commented
Further suggestion I forgot earlier: The `DEFAULT_PROFILE` should be removed since it's now unused.

2017-10-04 19:04 UTC, alexanderelliott121 commented on lib/health-data-standards/util/vs_api.rb
> +        if profile.nil? && include_draft
I think that the options.fetch(:profile, nil) returns a nil if there is an empty string.
I'll do some testing.

2017-10-05 01:48 UTC, c-monkey commented
I agree with all of @hossenlopp comments. Definitely put in some negative tests. Also the JIRA ticket says "It doesn't make sense for HDS to have a default profile...It's Bonnie's business to have a default profile." So might as well clean up the function description along with the DEFAULT_PROFILE.

Thanks!

2017-10-05 01:50 UTC, c-monkey requested changes
I agree with all of @hossenlopp comments. Definitely put in some negative tests. Also the JIRA ticket says "It doesn't make sense for HDS to have a default profile...It's Bonnie's business to have a default profile." So might as well clean up the function description along with the DEFAULT_PROFILE.

Thanks!

2017-10-05 12:32 UTC, alexanderelliott121 commented on test/unit/util/vs_api_test.rb
>    def test_api_v2_with_include_draft_specified_profile
I'm going to create a separate JIRA for this, since it would change the scope of the changes, but I agree that is should be addressed.

2017-10-09 13:05 UTC, alexanderelliott121 commented
@c-monkey I'm not sure I follow what you mean by negative test cases.
Currently I test to make sure that the correct exception is thrown if the wrong arguments are provided.  Is there another negative case I'm missing?

2017-10-09 17:11 UTC, hossenlopp commented on lib/health-data-standards/util/vs_api.rb
>        # The VSAC V2 API needs a profile to be specified when using includeDraft. Future work on this
At least the first line of the comment should be removed since you removed the `DEFAULT_PROFILE`.

2017-10-10 14:27 UTC, hossenlopp approved these changes

2017-10-10 15:41 UTC, c-monkey commented on test/unit/util/vs_api_test.rb
>    def test_api_v2_with_include_draft_specified_profile
Please add the link to the separate JIRA.

2017-10-11 02:32 UTC, c-monkey requested changes
We decided during the sprint review that if it is expedient, you should just finish up the testing before this PR is accepted. I propose only a few changes:

1) Following up on the request from @hossenlopp I did a little researching, and there is no such thing as asserting that an error wasn't thrown. True, we could create a try/catch block, BUT, if the error were thrown in another test, it would trigger an error, so it's not necessary to test. If desired, we could add a comment to the affect of: `# does not raise HealthDataStandards::Util::MalformedVSQueryError` or somesuch into test test_api_v2_with_include_draft_default_profile.

2) These tests miss a little of the logic, and could be revised to capture all logic permutations, but `get_valueset` is a very simple function. The tests are using the implicit matching of the parameters to the the call to `get_valueset` and the expected parameters in the `.with` of the `stub_request`. Since I was new to the WebMock library, didn't know there was no way to inspect parameters that were sent to the mocked URLs, so this use of WebMock is pretty clever.

3) For completeness, one could test that the stub *isn't* called, i.e.:
```
  def test_api_v2_with_include_draft_no_profile
    the_stub = stub_request(:get,'https://localhost/vsservice')
    api = HealthDataStandards::Util::VSApiV2.new("https://localhost/token", "https://localhost/vsservice", "myusername", "mypassword")
    assert_raises HealthDataStandards::Util::MalformedVSQueryError do
      api.get_valueset("oid", include_draft: true)
    end
    assert_not_requested the_stub
  end
```
Do you have an objection to this? I think it adds clarity.

Thanks,
--Chris

p.s. all tests in HDS and in Bonnie pass.

2017-10-12 12:07 UTC, edeyoung commented
What's the status on the regression tests?

2017-10-12 16:34 UTC, c-monkey commented
@alexanderelliott121 I'm concerned that the tests on the server are failing. Have you investigated?

2017-10-12 16:51 UTC, c-monkey approved these changes

2017-10-12 16:52 UTC, c-monkey commented
I have added a new JIRA ticket for the travis failures, I don't know if it's redundant to Matt's bonnie_bundler issue, but this one is for HDS: https://jira.mitre.org/browse/BONNIE-1140

2017-10-12 17:32 UTC, hossenlopp requested changes

2017-10-12 17:32 UTC, hossenlopp commented on test/unit/util/vs_api_test.rb
>      api.get_valueset("oid", include_draft: true, :profile=>"Most Recent CS Versions") do |oid,vs|
The result of calling get_valuset should be checked instead of asserting stuff in the block. If get_valueset doesn't actually attempt to get the valueset and just returns nothing, this test won't catch that since the block won't get called at all.

2017-10-12 17:41 UTC, c-monkey commented on test/unit/util/vs_api_test.rb
>      api.get_valueset("oid", include_draft: true, :profile=>"Most Recent CS Versions") do |oid,vs|
This is a problem in all the tests, then. I know you (@hossenlopp) caught this before but when debugging how the strange stub_request code works, I forgot about this very base case. Since the first parameter `oid` is not changed, we could make a simple test for testing the yield and then in all the rest of these tests just use the normal return value. Removing the, now basically worthless `assert_equal "oid", oid` assertions would be nice for cleaning up the code, too.

So, just change all the calls to `get_valueset` to `vs = ...` and remove the block. Then the one assertion in the block out-dented.

2017-10-13 12:35 UTC, alexanderelliott121 commented on test/unit/util/vs_api_test.rb
>      api.get_valueset("oid", include_draft: true, :profile=>"Most Recent CS Versions") do |oid,vs|
Basically, I think making that change should constitute its own ticket, given its scope.

2017-10-13 22:58 UTC, c-monkey commented on test/unit/util/vs_api_test.rb
>      api.get_valueset("oid", include_draft: true, :profile=>"Most Recent CS Versions") do |oid,vs|
@hossenlopp 's suggested refactor is trivial, changing 4 tests, each only 2 lines, and identical changes. I disagree that this should be taken out of this PR. The new Bonnie Way is to fix broken tests before we commit.

2017-10-16 14:28 UTC, alexanderelliott121 commented on test/unit/util/vs_api_test.rb
> +    valueset_xml = %{<?xml version="1.0" encoding="UTF-8"?><RetrieveValueSetResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" cacheExpiration
I needed to put it back in for the assert_not_requested.

2017-10-16 14:29 UTC, alexanderelliott121 commented
Tests have been updated.

2017-10-16 16:24 UTC, c-monkey approved these changes
Tested bonnie as well

2017-10-16 16:35 UTC, hossenlopp approved these changes

2017-10-16 16:41 UTC, merged