cql4bonnie dependency updates
MeasureAuthoringTool/health-data-standards pull request #549
Opened 2017-10-09 17:22 UTC by holmesie

2017-10-12 12:38 UTC, hossenlopp commented on lib/health-data-standards/export/helper/html_view_helper.rb
> +	    definition = HealthDataStandards::Util::HQMFTemplateHelper.definition_for_template_id(oid)
Indentation was dropped by one space in this block and the two other similar blocks. This is apparent in comparing the two branches with 'git' instead of trusting github.

2017-10-12 12:41 UTC, hossenlopp commented on lib/health-data-standards/export/qrda/hqmf-qrda-oids.json
> +    "hqmf_oid": "2.16.840.1.113883.10.20.28.3.24",
This OID changed, should it have?

2017-10-12 12:44 UTC, hossenlopp commented on lib/health-data-standards/export/qrda/hqmf-qrda-oids.json
> +    "hqmf_name": "Assessment, Performed",
"Assessment, Performed" and "Assessment, Recommended" are new in this branch.

2017-10-12 12:49 UTC, hossenlopp commented on lib/health-data-standards/export/view_helper.rb
> +        unless entry['negationInd'] == true
Putting things in this `unless entry['negationInd'] == true`  block is new to cql4bonnie, is there as risk of this interfering with the other negation stuff we have done?

2017-10-12 12:50 UTC, hossenlopp commented on lib/health-data-standards/export/view_helper.rb
> +        if entry['negationInd'] == true
This part of the if/else is new. Same question as above.

2017-10-12 12:52 UTC, hossenlopp commented on lib/health-data-standards/import/bulk_record_importer.rb
> +	          status = self.import_file(entry.name,data,failed_dir)
Indenting?

2017-10-12 13:08 UTC, hossenlopp commented on lib/health-data-standards/models/provider.rb
> +  CCN_OID = '2.16.840.1.113883.4.336'.freeze
Why is `.freeze` being called on this constant and not the others?

2017-10-12 13:11 UTC, hossenlopp commented on lib/health-data-standards/models/record.rb
> +  field :bundle_id, type: BSON::ObjectId
This makes sense since in Mongoid 5 all fields need to be defined. It won't store extra stuff you add.

2017-10-12 14:48 UTC, hossenlopp commented on lib/hqmf-parser/2.0/document.rb
> +      @cms_id = "CMS#{value}v#{@hqmf_version_number}" if (name.include? 'eMeasure Identifier') || (name.include? 'eCQM Identifier')
The usage of the `@hqmf_version_number` should be include `.to_i` to match the change to preserve the semantic versioning in the version number, but only in the `hqmf_version_number` field. https://github.com/projectcypress/health-data-standards/commit/c263be4e1fec6f94a6387cb89e359566f54fc411

2017-10-12 18:14 UTC, hossenlopp commented on lib/hqmf-parser/2.0/document.rb
> +      @cms_id = "CMS#{value}v#{@hqmf_version_number}" if (name.include? 'eMeasure Identifier') || (name.include? 'eCQM Identifier')
Not that this will fix the semantic version showing up in the title bars.

2017-10-16 17:12 UTC, hossenlopp commented on lib/health-data-standards/export/qrda/hqmf-qrda-oids.json
> +    "hqmf_oid": "2.16.840.1.113883.10.20.28.3.24",
This checks out.

2017-10-16 17:13 UTC, hossenlopp commented on lib/health-data-standards/export/qrda/hqmf-qrda-oids.json
> +    "hqmf_name": "Assessment, Performed",
This checks out.

2017-10-16 17:18 UTC, hossenlopp commented on lib/health-data-standards/export/view_helper.rb
> +        unless entry['negationInd'] == true
This checks out.

2017-10-16 17:18 UTC, hossenlopp commented on lib/health-data-standards/export/view_helper.rb
> +        if entry['negationInd'] == true
This checks out.

2017-10-16 17:22 UTC, hossenlopp commented on lib/health-data-standards/models/provider.rb
> +  CCN_OID = '2.16.840.1.113883.4.336'.freeze
Not worrying about this.

2017-10-16 17:24 UTC, hossenlopp commented on lib/health-data-standards/models/record.rb
> +  field :bundle_id, type: BSON::ObjectId
Non-issue.

2017-10-17 12:35 UTC, okeefm requested changes
This Pull Request adds the [Ruby Safe Naviagation Operator](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/) (`&.`), a language construct added in Ruby 2.3+. As such, Travis fails on both Rubies it runs, which are `2.1.1` and `2.2.4`. Since bonnie uses 2.3 (and both of those versions of Ruby are out of date, and End of Life/near it), I'd argue we should remove both of those Ruby versions from `.travis.yml` and add in only `2.3`.

2017-10-18 12:51 UTC, mayerm94 submitted a review, later dismissed
Regression works, JIRA tests have been run.

2017-10-18 13:26 UTC, okeefm submitted a review, later dismissed

2017-10-18 16:39 UTC, hossenlopp submitted a review, later dismissed

2017-10-20 19:12 UTC, hossenlopp approved these changes

2017-10-20 19:19 UTC, mayerm94 approved these changes

2017-10-20 19:30 UTC, merged