Assessment results
MeasureAuthoringTool/health-data-standards pull request #568
Opened 2018-04-10 21:57 UTC by dczulada

Pull requests into Health Data Standards require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.
 
**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] Internal ticket for this PR:
- [ ] Internal ticket links back to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass
- [ ] Code coverage has not gone down and all code touched or added is covered.
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here:
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here:
 
**Cypress Reviewer:**
 
Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code
 
**Bonnie Reviewer:**
 
Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2018-04-19 12:55 UTC, edeyoung requested changes
Please see comment re id. Not sure if it needs to be changed or not.

2018-04-19 12:55 UTC, edeyoung commented on templates/cat1/r4/_results.cat1.erb
> +     <id root="1.3.6.1.4.1.115" extension="<%= identifier_for(value) %>"/>
`id root="..."` appears to be different in the QRDA r4 example.
In the examples, it's `<id root="ed971e73-c060-4258-8838-69c830254b5a" />`

2018-05-09 17:09 UTC, edeyoung commented
Original:

```
<entry>
<observation classCode="OBS" moodCode="EVN">
<!--  Assessment Performed  -->
<templateId root="2.16.840.1.113883.10.20.24.3.144" extension="2016-08-01"/>
<id root="1.3.6.1.4.1.115" extension="594855bcb84846433c0fa406"/>
<code code="72136-5" codeSystem="2.16.840.1.113883.6.1" sdtc:valueSet="2.16.840.1.113883.3.117.1.7.1.357">
<originalText>Assessment, Performed: Vte Risk Assessment</originalText>
<translation code="72136-5" codeSystem="2.16.840.1.113883.6.1"/>
</code>
<text>Assessment, Performed: Vte Risk Assessment</text>
<statusCode code="completed"/>
<effectiveTime>
<low value="20121206063000"/>
<high value="20121206064500"/>
</effectiveTime>
<value code="62482003" codeSystem="2.16.840.1.113883.6.96" xsi:type="CD" sdtc:valueSet="2.16.840.1.113883.3.117.1.7.1.400">
<originalText>Low Risk</originalText>
</value>
</observation>
</entry>
```

Modified:
```
<entry>
<observation classCode="OBS" moodCode="EVN">
<!--  Assessment Performed  -->
<templateId root="2.16.840.1.113883.10.20.24.3.144" extension="2016-08-01"/>
<id root="1.3.6.1.4.1.115" extension="594855bcb84846433c0fa406"/>
<code code="72136-5" codeSystem="2.16.840.1.113883.6.1" sdtc:valueSet="2.16.840.1.113883.3.117.1.7.1.357">
<originalText>Assessment, Performed: Vte Risk Assessment</originalText>
<translation code="72136-5" codeSystem="2.16.840.1.113883.6.1"/>
</code>
<text>Assessment, Performed: Vte Risk Assessment</text>
<statusCode code="completed"/>
<effectiveTime>
<low value="20121206063000"/>
<high value="20121206064500"/>
</effectiveTime>
<entryRelationship typeCode="REFR">
<observation classCode="OBS" moodCode="EVN">
<!--  Conforms to C-CDA R2 Result Observation (V2)  -->
<templateId root="2.16.840.1.113883.10.20.22.4.2" extension="2015-08-01"/>
<!--  Result (QRDA I R3)  -->
<templateId root="2.16.840.1.113883.10.20.24.3.87" extension="2016-02-01"/>
<id root="1.3.6.1.4.1.115" extension="04131FBB7DF43DCF70047600DC597C97"/>
<code code="72136-5" codeSystem="2.16.840.1.113883.6.1" sdtc:valueSet="2.16.840.1.113883.3.117.1.7.1.357">
<originalText>Assessment, Performed: Vte Risk Assessment</originalText>
<translation code="72136-5" codeSystem="2.16.840.1.113883.6.1"/>
</code>
<statusCode code="completed"/>
<effectiveTime>
<low value="20121206063000"/>
<high value="20121206064500"/>
</effectiveTime>
<value code="62482003" codeSystem="2.16.840.1.113883.6.96" xsi:type="CD" sdtc:valueSet="2.16.840.1.113883.3.117.1.7.1.400">
<originalText>Low Risk</originalText>
</value>
</observation>
</entryRelationship>
</observation>
</entry>
```

Looks ok to me

2018-05-09 17:10 UTC, edeyoung approved these changes

2018-05-09 18:45 UTC, okeefm approved these changes
The ID change makes sense to me--IDs should be the same if elements have the same value, different otherwise, which is why the `identifier_for` function exists.

2018-05-09 19:32 UTC, merged