Add setting attribute to medication
MeasureAuthoringTool/health-data-standards pull request #595
Opened 2018-08-09 18:15 UTC by mayerm94

Setting code attribute was added to MedicationOrder in QDM5.4
Pull requests into Health Data Standards require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.
 
**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] Internal ticket for this PR: https://jira.mitre.org/browse/BONNIE-1656
- [ ] Internal ticket links back to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] Tests are included and test edge cases 
- [x] Tests have been run locally and pass
- [x] Code coverage has not gone down and all code touched or added is covered.
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here:
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here:
 
**Cypress Reviewer:**
 
Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code
 
**Bonnie Reviewer:**
 
Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2018-08-09 19:12 UTC, edeyoung commented on test/unit/models/medication_test.rb
> + class ProcedureTest < Minitest::Test
should be named `MedicationTest`

2018-08-09 19:14 UTC, edeyoung reviewed
small typo - other than that looks good

2018-08-09 19:32 UTC, edeyoung requested changes
see comment

2018-08-10 12:09 UTC, edeyoung approved these changes

2018-08-10 14:46 UTC, dczulada commented on test/unit/models/medication_test.rb
> +  def test_anatomical_approach_not_present
Is this test name accurate?

seems like name should be test_setting_not_present

2018-08-10 14:47 UTC, dczulada requested changes
Small change for name of testing the setting.

2018-08-13 13:25 UTC, dczulada approved these changes

2018-08-13 13:33 UTC, merged